name: 'Create release'

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    name: 'Release for ${{ matrix.os }}'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: 'Build python artefacts'
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: false
          outputs: 'type=local,dest=build-output'
      - name: 'Generate changelog'
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Read python artefact versions'
        id: read-version
        run: |
          cd python
          python setup.py --version
          echo ::set-output name=artefact-version::$( python setup.py --version )
      - name: 'Create Release'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read-version.outputs.artefact-version }}
          name: Release ${{ steps.read-version.outputs.artefact-version }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            build-output/pyecsim-${{ steps.read-version.outputs.artefact-version }}-*.whl